### ISSUE TITLE
Issue when downloading data

### ISSUE THREAD

**Issue by marker1401** [ZhengyaoJiang/PGPortfolio#121]
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    main()
  File "main.py", line 81, in main
    portion_reversed=config["input"]["portion_reversed"])
  File "C:\PGPortfolio-master(1)\PGPortfolio-master\pgportfolio\marketdata\datamatrices.py", line 51, in __init__
    features=type_list)
  File "C:\PGPortfolio-master(1)\PGPortfolio-master\pgportfolio\marketdata\globaldatamatrix.py", line 62, in get_global_panel
    self.update_data(start, end, coin)
  File "C:\PGPortfolio-master(1)\PGPortfolio-master\pgportfolio\marketdata\globaldatamatrix.py", line 176, in update_data
    self.__fill_data(start, end, coin, cursor)
  File "C:\PGPortfolio-master(1)\PGPortfolio-master\pgportfolio\marketdata\globaldatamatrix.py", line 201, in __fill_data
    if c["date"] > 0:
TypeError: string indices must be integers

cant figure out why the c["date"] line must be an integer when it seems to be a dictionary
help would be really appreciated

**Comment by marker1401** [comment]
THe issue has been discussed in #120
