### ISSUE TITLE
Segmentation fault  during plot mode

### ISSUE THREAD

**Issue by stevexxs** [ZhengyaoJiang/PGPortfolio#122]
run below command to plot.
python main.py --mode=plot --algos=crp,olmar,1 --labels=crp,olmar,nnagent
but segment fault happened,
looks like having some problem when calling Qt5.

```
(gdb) bt
#0  0x00007fffa5a4ddf7 in ?? () from /anaconda3/lib/libQt5XcbQpa.so.5
#1  0x00007fffa5a406fe in ?? () from /anaconda3/lib/libQt5XcbQpa.so.5
#2  0x00007fffa5a407d1 in ?? () from /anaconda3/lib/libQt5XcbQpa.so.5
#3  0x00007fffa5a39275 in QXcbConnection::QXcbConnection(QXcbNativeInterface*, bool, unsigned int, char const*) () from /anaconda3/lib/libQt5XcbQpa.so.5
#4  0x00007fffa5a3b7e4 in QXcbIntegration::QXcbIntegration(QStringList const&, int&, char**) () from /anaconda3/lib/libQt5XcbQpa.so.5
#5  0x00007fffa4e3062d in QXcbIntegrationPlugin::create(QString const&, QStringList const&, int&, char**) ()
   from /anaconda3/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so
#6  0x00007fffa99f1d5b in QPlatformIntegrationFactory::create(QString const&, QStringList const&, int&, char**, QString const&) ()
   from /anaconda3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#7  0x00007fffa99fe7b7 in QGuiApplicationPrivate::createPlatformIntegration() () from /anaconda3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#8  0x00007fffa99ff89d in QGuiApplicationPrivate::createEventDispatcher() () from /anaconda3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#9  0x00007fffacecfb4f in QCoreApplicationPrivate::init() () from /anaconda3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#10 0x00007fffa9a0123c in QGuiApplicationPrivate::init() () from /anaconda3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#11 0x00007fffa61ab489 in QApplicationPrivate::init() () from /anaconda3/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#12 0x00007fffa6ae3269 in sipQApplication::sipQApplication(int&, char**, int) () from /anaconda3/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#13 0x00007fffa6ae3339 in init_type_QApplication () from /anaconda3/lib/python3.6/site-packages/PyQt5/QtWidgets.so
#14 0x00007fffaa6aec74 in sipSimpleWrapper_init () from /anaconda3/lib/python3.6/site-packages/PyQt5/sip.so
#15 0x00005555556ec767 in type_call (type=<optimized out>, type@entry=0x555559759ab8, args=args@entry=0x7fffa5529358, kwds=kwds@entry=0x0)
    at /tmp/build/80754af9/python_1546130271559/work/Objects/typeobject.c:915
```

how to solve this issue ?

**Comment by dexhunter** [comment]
this issue seems to be out of scope of this repo
