### ISSUE TITLE
TypeError: object() takes no parameters

### ISSUE THREAD

**Issue by Tylersuard** [ZhengyaoJiang/PGPortfolio#136]
Ran this command:
!python main.py --mode=download_data

Result:

Traceback (most recent call last):
  File "main.py", line 132, in <module>
    main()
  File "main.py", line 81, in main
    portion_reversed=config["input"]["portion_reversed"])
  File "/content/PGPortfolio/pgportfolio/marketdata/datamatrices.py", line 51, in __init__
    features=type_list)
  File "/content/PGPortfolio/pgportfolio/marketdata/globaldatamatrix.py", line 72, in get_global_panel
    panel = pd.Panel(items=features, major_axis=coins, minor_axis=time_index, dtype=np.float32)
TypeError: object() takes no parameters

**Comment by Tylersuard** [comment]
Solved by downgrading to pandas==0.20.3
